# ---- Frontend estático (HTML/CSS/JS) ----
FROM nginx:1.27-alpine

# Copiamos tu carpeta con index.html, script.js, estilos.css, imágenes, etc.
COPY jarvis_frontend/ /usr/share/nginx/html

# Si necesitas un nginx.conf custom, descomenta estas líneas:
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 88
CMD ["nginx", "-g", "daemon off;"]
